config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :songs
  resources :genres do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :songs
end

app/models/genres_songs.rb
class GenresSongs < ApplicationRecord
  belongs_to :genre
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  has_and_belongs_to_many :genres
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @genre_id = params[:genre_id]

    if @genre_id.nil?
      @songs = Song.all
    else
      @songs = Song.where(genre_id: @genre_id)
    end

  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @genres = Genre.all
  end

  def create
    @song = Song.new(song_params)
    @song.save

    redirect_to @song
  end

  private
  def song_params
    params.require(:song).permit(:name, :genre_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/genres/index.html.erb
<% @genres.each do |genre| %>
  <p>
    <strong>Name:</strong> <%= genre.name %>
  </p>
  <p>
    <strong>Description:</strong> <%= genre.description %>
  </p>
  <p>
    <strong>Songs:</strong>
      <ul>
        <% genre.song.each do |song| %>
          <li><%= song.name %></li>
        <% end %>
      </ul>

  </p>
  <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sortify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<% @songs.each do |song| %>
  <p><b>SONG</b></p>
  <p><%= song.name %></p>
  GENRES:
  <% song.genres.each do |genre| %>
    <%= genre.name %>
  <% end %>
<% end %>

app/views/songs/new.html.erb
<%= form_with scope: :song, url: songs_path, local: true do |form| %>

  <%= form.collection_check_boxes :genre_ids, @genres, :id, :name %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_area :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/songs/show.html.erb
<p><%= @song.name %></p>

gneres: 
<% @song.genres.each do |genre| %>

    <%= genre.name %>

<% end %>